const dashboardData = {
  stats: {
    totalProperties: 1247,
    totalUsers: 8563,
    totalRevenue: 45289000,
    pendingApprovals: 23,
    monthlyGrowth: 12.5,
    userGrowth: 8.2,
    activeListings: 892,
    conversionRate: 18.4,
  },
  revenueData: [
    { month: "Jan", revenue: 4000000, expenses: 2500000 },
    { month: "Feb", revenue: 5200000, expenses: 2800000 },
    { month: "Mar", revenue: 6100000, expenses: 3200000 },
    { month: "Apr", revenue: 7800000, expenses: 3800000 },
    { month: "May", revenue: 8900000, expenses: 4200000 },
    { month: "Jun", revenue: 9500000, expenses: 4500000 },
    { month: "Jul", revenue: 11200000, expenses: 5100000 },
    { month: "Aug", revenue: 12500000, expenses: 5800000 },
  ],
  propertyTypeData: [
    { name: "Apartments", value: 35, color: "#3b82f6" },
    { name: "Duplex", value: 25, color: "#10b981" },
    { name: "Bungalow", value: 15, color: "#f59e0b" },
    { name: "Commercial", value: 12, color: "#ef4444" },
    { name: "Plots", value: 8, color: "#8b5cf6" },
    { name: "Others", value: 5, color: "#06b6d4" },
  ],
  locationData: [
    { city: "Lagos", properties: 456, growth: 15 },
    { city: "Abuja", properties: 389, growth: 12 },
    { city: "Port Harcourt", properties: 234, growth: 8 },
    { city: "Ibadan", properties: 198, growth: 6 },
    { city: "Kano", properties: 156, growth: 4 },
  ],
  userActivity: [
    { time: "9:00", users: 45, pageViews: 234 },
    { time: "10:00", users: 78, pageViews: 345 },
    { time: "11:00", users: 112, pageViews: 512 },
    { time: "12:00", users: 98, pageViews: 423 },
    { time: "13:00", users: 134, pageViews: 645 },
    { time: "14:00", users: 156, pageViews: 723 },
    { time: "15:00", users: 145, pageViews: 612 },
    { time: "16:00", users: 167, pageViews: 734 },
  ],
  performanceMetrics: [
    { subject: "Sales", A: 120, fullMark: 150 },
    { subject: "Marketing", A: 98, fullMark: 150 },
    { subject: "Support", A: 86, fullMark: 150 },
    { subject: "Dev", A: 99, fullMark: 150 },
    { subject: "Design", A: 85, fullMark: 150 },
    { subject: "Analytics", A: 95, fullMark: 150 },
  ],
  topProperties: [
    { id: 1, name: "Luxury Villa in Lekki", views: 2450, leads: 48 },
    { id: 2, name: "Modern Apartment Abuja", views: 2180, leads: 42 },
    { id: 3, name: "Commercial Space VI", views: 1920, leads: 38 },
    { id: 4, name: "Duplex in Ikoyi", views: 1750, leads: 35 },
    { id: 5, name: "Bungalow Port Harcourt", views: 1580, leads: 31 },
  ],
};

export const dummyProperties = [
  {
    _id: "1",
    propertyId: "NGPROP001",
    title: "Luxury 3 Bedroom Apartment in Lekki",
    description:
      "Beautiful modern apartment with stunning ocean views, fully furnished with premium amenities.",
    address: {
      street: "12 Admiralty Way",
      area: "Lekki Phase 1",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    location: {
      type: "Point",
      coordinates: [3.4513, 6.4413], // Lekki coordinates
    },
    propertyType: "Flat/Apartment",
    flatType: "3 Bedroom",
    bedrooms: 3,
    bathrooms: 3,
    price: {
      amount: 85000000,
      currency: "NGN",
      negotiable: true,
    },
    listingType: "For Sale",
    furnishingStatus: "Fully Furnished",
    propertyCondition: "Excellent",
    amenities: ["Swimming Pool", "Gym", "Security", "CCTV", "Generator"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=500",
        type: "image",
        category: "exterior",
        subCategory: "cover",
        isPrimary: true,
      },
    ],
    views: 2450,
    saves: 48,
    inquiries: 23,
    approvalStatus: "Approved",
    isVerified: true,
    availableFrom: new Date(),
    createdAt: new Date("2024-01-15"),
  },
  {
    _id: "2",
    propertyId: "NGPROP002",
    title: "Modern Duplex in Ikeja GRA",
    description:
      "Spacious duplex with elegant finish, located in the heart of Ikeja GRA.",
    address: {
      street: "5 Oba Akinjobi Way",
      area: "Ikeja GRA",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    location: {
      type: "Point",
      coordinates: [3.349, 6.6018], // Ikeja coordinates
    },
    propertyType: "Detached Duplex",
    bedrooms: 4,
    bathrooms: 4,
    price: {
      amount: 120000000,
      currency: "NGN",
      negotiable: false,
    },
    listingType: "For Sale",
    furnishingStatus: "Semi-Furnished",
    propertyCondition: "New",
    amenities: ["Garden", "Security", "Generator", "Borehole"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=500",
        type: "image",
        category: "exterior",
        subCategory: "cover",
        isPrimary: true,
      },
    ],
    views: 1890,
    saves: 35,
    inquiries: 18,
    approvalStatus: "Approved",
    isVerified: true,
    availableFrom: new Date(),
    createdAt: new Date("2024-02-10"),
  },
  {
    _id: "3",
    propertyId: "NGPROP003",
    title: "2 Bedroom Flat for Rent in Victoria Island",
    description:
      "Cozy apartment in secure estate, perfect for young professionals.",
    address: {
      street: "23A Adeola Odeku",
      area: "Victoria Island",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    location: {
      type: "Point",
      coordinates: [3.4255, 6.4281], // VI coordinates
    },
    propertyType: "Flat/Apartment",
    flatType: "2 Bedroom",
    bedrooms: 2,
    bathrooms: 2,
    price: {
      amount: 4500000,
      currency: "NGN",
      negotiable: true,
    },
    listingType: "For Rent",
    rentalDetails: {
      depositAmount: 4500000,
      rentFrequency: "Yearly",
      petsAllowed: false,
    },
    furnishingStatus: "Fully Furnished",
    propertyCondition: "Excellent",
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "CCTV"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500",
        type: "image",
        category: "exterior",
        subCategory: "cover",
        isPrimary: true,
      },
    ],
    views: 3120,
    saves: 67,
    inquiries: 42,
    approvalStatus: "Approved",
    isVerified: true,
    availableFrom: new Date(),
    createdAt: new Date("2024-01-28"),
  },
  {
    _id: "4",
    propertyId: "NGPROP004",
    title: "Commercial Space in Abuja Central",
    description:
      "Prime commercial space suitable for office or retail business.",
    address: {
      street: "Plot 123 Central Area",
      area: "Central Business District",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
    },
    location: {
      type: "Point",
      coordinates: [7.4951, 9.0579], // Abuja coordinates
    },
    propertyType: "Commercial",
    bedrooms: 0,
    bathrooms: 2,
    price: {
      amount: 75000000,
      currency: "NGN",
      negotiable: true,
    },
    listingType: "For Sale",
    furnishingStatus: "Unfurnished",
    propertyCondition: "Good",
    amenities: ["Security", "CCTV", "Generator", "Parking"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=500",
        type: "image",
        category: "exterior",
        subCategory: "cover",
        isPrimary: true,
      },
    ],
    views: 1560,
    saves: 28,
    inquiries: 15,
    approvalStatus: "Pending",
    isVerified: false,
    availableFrom: new Date(),
    createdAt: new Date("2024-03-01"),
  },
  {
    _id: "5",
    propertyId: "NGPROP005",
    title: "Bungalow in Port Harcourt GRA",
    description:
      "Beautiful 3-bedroom bungalow with large compound and modern amenities.",
    address: {
      street: "15 Nnadi Azikiwe Road",
      area: "GRA Phase 2",
      city: "Port Harcourt",
      state: "Rivers",
      country: "Nigeria",
    },
    location: {
      type: "Point",
      coordinates: [7.0134, 4.8156], // Port Harcourt coordinates
    },
    propertyType: "Bungalow",
    bedrooms: 3,
    bathrooms: 3,
    price: {
      amount: 65000000,
      currency: "NGN",
      negotiable: true,
    },
    listingType: "For Sale",
    furnishingStatus: "Semi-Furnished",
    propertyCondition: "Excellent",
    amenities: ["Garden", "Security", "Borehole", "Generator"],
    media: [
      {
        url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=500",
        type: "image",
        category: "exterior",
        subCategory: "cover",
        isPrimary: true,
      },
    ],
    views: 1780,
    saves: 32,
    inquiries: 19,
    approvalStatus: "Approved",
    isVerified: true,
    availableFrom: new Date(),
    createdAt: new Date("2024-02-22"),
  },
];

export const mockUsers = [
  {
    _id: "1",
    fullName: "John Smith",
    email: "john.smith@example.com",
    phone: "+1 (555) 123-4567",
    roles: ["buyer", "seller"],
    activeRole: "buyer",
    profilePhoto: "",
    verified: true,
    createdAt: "2024-01-15T10:30:00Z",
    lastLogin: "2024-03-20T14:22:00Z",
    savedProperties: ["prop1", "prop2"],
    agentProfile: null,
    estateProfile: null,
  },
  {
    _id: "2",
    fullName: "Sarah Johnson",
    email: "sarah.j@example.com",
    phone: "+1 (555) 234-5678",
    roles: ["agent"],
    activeRole: "agent",
    profilePhoto: "",
    verified: true,
    createdAt: "2024-02-10T08:15:00Z",
    lastLogin: "2024-03-20T09:45:00Z",
    savedProperties: ["prop3"],
    agentProfile: {
      licenseNumber: "AG123456",
      agencyName: "Premium Realty",
      yearsOfExperience: 5,
      specializations: ["residential", "luxury"],
      ratings: 4.8,
      reviewsCount: 127,
      verified: true,
    },
    estateProfile: null,
  },
  {
    _id: "3",
    fullName: "Mike Chen",
    email: "mike.chen@example.com",
    phone: "+1 (555) 345-6789",
    roles: ["estate"],
    activeRole: "estate",
    profilePhoto: "",
    verified: false,
    createdAt: "2024-03-01T16:20:00Z",
    lastLogin: "2024-03-18T11:30:00Z",
    savedProperties: [],
    agentProfile: null,
    estateProfile: {
      estateName: "Elite Properties Group",
      address: "123 Business Ave, New York, NY",
      contactEmail: "contact@eliteproperties.com",
      phone: "+1 (555) 999-8888",
      registrationNumber: "EST789012",
      totalProperties: 45,
      verified: false,
    },
  },
  {
    _id: "4",
    fullName: "Emma Davis",
    email: "emma.davis@example.com",
    phone: "+1 (555) 456-7890",
    roles: ["buyer", "seller", "agent"],
    activeRole: "agent",
    profilePhoto: "",
    verified: true,
    createdAt: "2024-01-28T12:00:00Z",
    lastLogin: "2024-03-20T16:15:00Z",
    savedProperties: ["prop4", "prop5", "prop6"],
    agentProfile: {
      licenseNumber: "AG789012",
      agencyName: "City Homes Realty",
      yearsOfExperience: 3,
      specializations: ["residential", "rental"],
      ratings: 4.5,
      reviewsCount: 89,
      verified: true,
    },
    estateProfile: null,
  },
  {
    _id: "5",
    fullName: "Robert Wilson",
    email: "rob.wilson@example.com",
    phone: "+1 (555) 567-8901",
    roles: ["buyer"],
    activeRole: "buyer",
    profilePhoto: "",
    verified: false,
    createdAt: "2024-03-15T14:45:00Z",
    lastLogin: "2024-03-19T10:20:00Z",
    savedProperties: ["prop7"],
    agentProfile: null,
    estateProfile: null,
  },
];

export default dashboardData;
